services:
  gitsearch-app:
    image: node:20
    container_name: gitsearch-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "5173:5173"
    command: bash -c "yarn install && yarn dev"
