services:
  gitsearch-app:
    image: node:20
    container_name: gitsearch-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "5173:5173"
    command: bash -c "yarn install && yarn dev"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: gitsearch-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gitsearch
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
